/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FixesRouteImport } from './routes/fixes'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as ApiSummaryRouteImport } from './routes/api/summary'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFixRouteImport } from './routes/api/fix'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiSummaryAnalysisIdRouteImport } from './routes/api/summary.$analysisId'
import { Route as ApiReportIdRouteImport } from './routes/api/report.$id'
import { Route as ApiHistoryIdRouteImport } from './routes/api/history.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FixesRoute = FixesRouteImport.update({
  id: '/fixes',
  path: '/fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryRoute = ApiSummaryRouteImport.update({
  id: '/api/summary',
  path: '/api/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixRoute = ApiFixRouteImport.update({
  id: '/api/fix',
  path: '/api/fix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryAnalysisIdRoute = ApiSummaryAnalysisIdRouteImport.update({
  id: '/$analysisId',
  path: '/$analysisId',
  getParentRoute: () => ApiSummaryRoute,
} as any)
const ApiReportIdRoute = ApiReportIdRouteImport.update({
  id: '/api/report/$id',
  path: '/api/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryIdRoute = ApiHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/check-email': typeof CheckEmailRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fix': typeof ApiFixRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/summary': typeof ApiSummaryRouteWithChildren
  '/issues/$id': typeof IssuesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/report/$id': typeof ApiReportIdRoute
  '/api/summary/$analysisId': typeof ApiSummaryAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/check-email': typeof CheckEmailRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fix': typeof ApiFixRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/summary': typeof ApiSummaryRouteWithChildren
  '/issues/$id': typeof IssuesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports': typeof ReportsIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/report/$id': typeof ApiReportIdRoute
  '/api/summary/$analysisId': typeof ApiSummaryAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/check-email': typeof CheckEmailRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/fix': typeof ApiFixRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/summary': typeof ApiSummaryRouteWithChildren
  '/issues/$id': typeof IssuesIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/history/$id': typeof ApiHistoryIdRoute
  '/api/report/$id': typeof ApiReportIdRoute
  '/api/summary/$analysisId': typeof ApiSummaryAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/check-email'
    | '/fixes'
    | '/history'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/reset-password'
    | '/settings'
    | '/sign-up'
    | '/api/analyze'
    | '/api/fix'
    | '/api/history'
    | '/api/summary'
    | '/issues/$id'
    | '/reports/$id'
    | '/reports/'
    | '/api/history/$id'
    | '/api/report/$id'
    | '/api/summary/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/check-email'
    | '/fixes'
    | '/history'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/reset-password'
    | '/settings'
    | '/sign-up'
    | '/api/analyze'
    | '/api/fix'
    | '/api/history'
    | '/api/summary'
    | '/issues/$id'
    | '/reports/$id'
    | '/reports'
    | '/api/history/$id'
    | '/api/report/$id'
    | '/api/summary/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/check-email'
    | '/fixes'
    | '/history'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/reset-password'
    | '/settings'
    | '/sign-up'
    | '/api/analyze'
    | '/api/fix'
    | '/api/history'
    | '/api/summary'
    | '/issues/$id'
    | '/reports/$id'
    | '/reports/'
    | '/api/history/$id'
    | '/api/report/$id'
    | '/api/summary/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CheckEmailRoute: typeof CheckEmailRoute
  FixesRoute: typeof FixesRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignUpRoute: typeof SignUpRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiFixRoute: typeof ApiFixRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiSummaryRoute: typeof ApiSummaryRouteWithChildren
  IssuesIdRoute: typeof IssuesIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ApiReportIdRoute: typeof ApiReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixes': {
      id: '/fixes'
      path: '/fixes'
      fullPath: '/fixes'
      preLoaderRoute: typeof FixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary': {
      id: '/api/summary'
      path: '/api/summary'
      fullPath: '/api/summary'
      preLoaderRoute: typeof ApiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fix': {
      id: '/api/fix'
      path: '/api/fix'
      fullPath: '/api/fix'
      preLoaderRoute: typeof ApiFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary/$analysisId': {
      id: '/api/summary/$analysisId'
      path: '/$analysisId'
      fullPath: '/api/summary/$analysisId'
      preLoaderRoute: typeof ApiSummaryAnalysisIdRouteImport
      parentRoute: typeof ApiSummaryRoute
    }
    '/api/report/$id': {
      id: '/api/report/$id'
      path: '/api/report/$id'
      fullPath: '/api/report/$id'
      preLoaderRoute: typeof ApiReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$id': {
      id: '/api/history/$id'
      path: '/$id'
      fullPath: '/api/history/$id'
      preLoaderRoute: typeof ApiHistoryIdRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
  }
}

interface ApiHistoryRouteChildren {
  ApiHistoryIdRoute: typeof ApiHistoryIdRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryIdRoute: ApiHistoryIdRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

interface ApiSummaryRouteChildren {
  ApiSummaryAnalysisIdRoute: typeof ApiSummaryAnalysisIdRoute
}

const ApiSummaryRouteChildren: ApiSummaryRouteChildren = {
  ApiSummaryAnalysisIdRoute: ApiSummaryAnalysisIdRoute,
}

const ApiSummaryRouteWithChildren = ApiSummaryRoute._addFileChildren(
  ApiSummaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CheckEmailRoute: CheckEmailRoute,
  FixesRoute: FixesRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignUpRoute: SignUpRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiFixRoute: ApiFixRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiSummaryRoute: ApiSummaryRouteWithChildren,
  IssuesIdRoute: IssuesIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ApiReportIdRoute: ApiReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
